### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by wachulski** [difi/idporten-oidc-dokumentasjon#24]
Could you please provide an English version of your documentation for non-natives? Also, could you translate and keep issues here English (not that much of them yet, so shouldn't be a big deal). 

It would much much easier for developers around the world to integrate with your solution.

**Comment by joergenb** [comment]
Hi. The intended audience for this documentation is Norwegian public sector, so Difi has previously taken a policy stance that ID-porten related documentation stays in Norwegian only - and part of their purpose is to provide a Norwegian "OIDC-for-norwegian-dummies" summary.

The OIDC spec's are easy to read, and the English there is anyway much better than our writing, so I would rather advise to read them directly, or the implementors guide here: https://openid.net/specs/openid-connect-basic-1_0.html.
