### ISSUE TITLE
usecase for server-til-server api-autorisasjon

### ISSUE THREAD

**Issue by rolfrander** [difi/idporten-oidc-dokumentasjon#40]
Hei, jeg er litt usikker på hva som er bruksområdet og gevinsten av å bruke ID-porten og JWT til server-til-server API-autorisasjon.

Slik jeg forstår dokumentasjonen bruker man et virksomhetssertifikat for å få utstedet et jwt-token, og så jwt-tokenet for å autentisere seg mot tjeneste.

Hva er gevinsten ved å gå via jwt, hvorfor ikke bare bruke virksomhetssertifikatet direkte til å signere forespørselen eller som TLS-klientsertifikat? (En signatur vil også gi ende-til-ende-integritet, uklart for meg om jwt kan gi dette).

**Comment by ingebrigt** [comment]
Enig i spørsmålet.

**Comment by aamundbr** [comment]
Hei.

Det er flere grunner til at det for oss er hensiktsmessig å skille mellom en autorisasjonsserver og ressursserver, og bruke en OAuth2 token-basert flyt til dette. 

Her er noen grunner:

1. OAuth2 gir en fin rollefordeling (separation of roles)

I vår kontekst har vi et stort antall kunder og vi har flere ulike produkter / tjenster som tilbyr api'er. Vi ønsker samme autorisasjonsmekanisme for disse, og en sentral tjeneste for å administrere klienter og tilganger. For noen api'er ønsker vi også å tilby ulike autentiseringsmåter (f.eks. brukes api'ene både i en maskin-2-maskin kontekst og i konteksten av en innlogget bruker til en webtjeneste.)

Bruksområdene medfører også ofte at klientene har flyter som involverer bruk av flere api'er. Vi ønsker også å kunne støtte eksterne api'er fra andre enn Difi i disse flytene.

Gitt i lys av disse forutsetningene finner vi det fornuftig å skille mellom rollene autorisasjonsserver og ressursserver.  Alternativet er at hver ressursserver / API-tjeneste må implementere sin egen autorisasjonsmekanisme (potensielt flere ulike), med den kompleksiteten det medfører. Denne bør ideelt sett være likt implementert på tvers av api'er osv.


2. Validering av signaturer og sertifikater koster

MERK: I vår kontekst er formålet med bruk av virksomhetssertifikater en sikker autentisering av klienten, ikke å ivareta integriteten i requesten.

Api'ene våre har ofte et bruksmønster der samme klient gjør flere oppslag innen et relativt kort tidsrom. Dersom autorisasjonsmekanismen for api'ene våre baserte seg på signerte requester fra klientene må signaturer og virksomhetssertifikatet valideres for hver request. Dette har en kostnad, som kan være stor mot å validere et token mot en intern autorisasjonsserver. Satt på spissen, det er en forskjell på å gjøre 300 signaturvalideringer og eksterne OCSP oppslag i sekundet mot å gjøre en noen få annenhvert minutt.


3. Dette følger standarder, og er likt slik som andre gjør det.

Det vi liker med denne metoden er at den er standardisert gjennom OAuth2 og OAuth2 JWT-profile RFC'ene, og disse får stadig mer oppmerksomhet. Dette er f.eks. samme metode som Google bruker for maskin-2-maskin tilgang til sine API'er.

Men som sagt, dette er noe som passer bra i vår kontekst og i forhold til de bruksmønsterene som er for våre api'er. Andre API-tilbydere må vudere hva som er hensiktsmessig for seg. Ditt forslag vil helt sikkert være et fornuftig alternativ i mange sammenhenger, og også gi litt bedre sikkerhet da du også får ivaretatt integriteten i requestene mot api'et.

**Comment by rolfrander** [comment]
Hei, takk for grundig svar. Dere kan selvsagt gjøre hva dere vil her, jeg ser dette i perspektivet fra andre etater som vurderer dette som alternativ til TLS-klientsertifikat. 

Jeg ser helt klart en gevinst ved å bruke en mekanisme på HTTP-laget fremfor TLS, men bortsett fra det er jeg fortsatt ikke overbevist:

# 1. rollefordeling
For en annen etat enn Difi ser jeg for meg at det blir både administrativt tungvindt og en vanskelig trusselmodell om autorisering skal administreres i ID-porten. Bruk av "scopes" og "on behalf of" gir helt klart mye fleksibilitet, men jeg ser for meg at i praksis vil mye autorisasjon måtte håndteres i tjenesten selv uansett (tilgangsstyring på objektnivå må integreres inn i tjenestens datastruktur). 

Ad klienter som bruker flere API: disse vil kreve token med forskjellig "audience", slik at det uansett må gjøres en separat autentisering og genereres et separat token per tjeneste.

Men bruk av samme mekanisme for brukere og systemer er en god ide, jeg skal tenke mer på dette.

# 2. validering av signaturer
Det er mulig jeg misforstår, men hvis man bruker et "self contained" token er det jo også en signatur som må valideres (men det kan hende at dette konseptuelt sett er enklere fordi tjenesten kun trenger forholde seg til ID-porten sitt sertifikat og ikke en hel sertifikatkjede). Og bruker man et "by reference" token må det gjøres et nettverkskall. Resultatet av dette kan sikkert caches, men hvis alternativet er TLS-klientsertifikat vil det typisk gjøres flere kall i samme TLS-sesjon.

Det vil også være mer jobb for klienten som først må signere en tokenforespørsel før den kan gjøre det faktiske tjenestekallet.

# 3. standarder
TLS-klientsertifikat er også en godt etablert standard.

**Comment by kjorlaug** [comment]
Det foregår eit arbeid under nasjonal arkitektur (https://www.difi.no/fagomrader-og-tjenester/digitalisering-og-samordning/nasjonal-arkitektur) der dei ser på forskjellige referansearkitekturar for digital samhandling. Eit av perspektiva der er underliggande sikkerheitsarkitektur, herunder fordeler/ulemper med dei forskjellige løysingane (både TLS og OpenIdConnect er med i diskusjonane). Tenker denne diskusjonen høyrer meir heime i det foraet (og ikkje her - heimen til dokumentasjonen til ein av dei). Alle dei store offentlege etatane er representert i dette arbeidet, så her kan de anten ta kontakt med rett miljø i Difi, eller argumentere internt for dykkar løysing (reknar med at de sit i eller jobbar for ein av dei). 

Generelt så er min kommentar at det er viktigare å belyse fordeler/ulemper med forskjellige arkitekturar, slik at ein velger ein på rett grunnlag, framfor at ein skal peike på ein som den beste (og obligatioriske).
