### ISSUE TITLE
Er eIDAS-støtte på plass i oidc-ver2.difi.no?

### ISSUE THREAD

**Issue by leivhe** [difi/idporten-oidc-dokumentasjon#57]
hei, https://oidc-ver2.difi.no/idporten-oidc-provider/.well-known/openid-configuration har ikkje "eidas" med i scopes_supported.

Det forklarar kanskje at eg får:
"invalid_scope" for `scope=openid eidas` og
"Invalid or unknown parameter value for parameter: login_hint" når eg legg til `login_hint={eidas:true}`

Er det dokumentasjonen det er noko gale med på https://difi.github.io/idporten-oidc-dokumentasjon/oidc_func_eidas.html ? Eller er det ikkje rulla ut enno?

mvh Leiv Hellebø
(programmerar hos UNIT)

**Comment by leivhe** [comment]
Forresten har dokumentasjonen "Eksempel på request" med `&scopes=openid eidas`. Det skal vel vere `scope` i eintal?

**Comment by eirikhoem** [comment]
Skal få sett på det i løpet av dagen

Eirik Hoem



22. nov. 2018 kl. 07:37 skrev Leiv Hellebo <notifications@github.com<mailto:notifications@github.com>>:


Forresten har dokumentasjonen "Eksempel på request" med &scopes=openid eidas. Det skal vel vere scope i eintal?

**Comment by leivhe** [comment]
Jørgen ba meg i epost prøve `login_hint=eidas:true`

Då får eg velge autentiseringsland. Bra. Men når eg vel Hellas (som eg har testbrukar for) blir eg redirigert til
https://eidas-test1.difi.eon.no/EidasNode/ServiceProvider og der får eg 

EIDAS AUTHENTICATION SERVICE
AN UNEXPECTED ERROR HAS OCCURRED
PLEASE REPORT THIS ERROR TO YOUR SYSTEM ADMINISTRATOR OR APPROPRIATE TECHNICAL SUPPORT PERSONNEL.
200006 - The SAML Request Token is missing or invalid.
THANK YOU FOR YOUR COOPERATION.

**Comment by joergenb** [comment]
du manglar sannsynlegvis å _ogso_ be om 'eidas'  scope,  dette trengs for å trigge 'avansert' eidas-oppførsel.  
i tillegg er det nokre reine feil i dokumentasjon, so den blir oppdatert.

**Comment by leivhe** [comment]
Men du ba meg jo ta bort eidas scope?!?? legg eg til det, får eg f.eks.
Type: invalid_scope. Description: (correlation id: 39c8296f-3c7b-568b-86ad-ce30603948e5)
