### ISSUE TITLE
Avbryt gir 203007 invalid SAML

### ISSUE THREAD

**Issue by leivhe** [difi/idporten-oidc-dokumentasjon#59]
Ei sak som ikkje gjeld dokumentasjonen (men kor elles kan eg sende den?)

Når eg klikker Avbryt/Cancel hos swedenconnect.se (etter å ha vald å autentisere mot svensk eIDAS-node), blir eg sendt tilbake til https://eidas-test1.difi.eon.no/EidasNode/ColleagueResponse og får Unexpected error: 203007 - The SAML message is not valid

**Comment by eirikhoem** [comment]
Send support-saker til idporten@difi.no<mailto:idporten@difi.no>
Web: samarbeid.difi.no

Eirik

Fra: Leiv Hellebo <notifications@github.com>
Sendt: torsdag 29. november 2018 12:54
Til: difi/idporten-oidc-dokumentasjon <idporten-oidc-dokumentasjon@noreply.github.com>
Kopi: Subscribed <subscribed@noreply.github.com>
Emne: [difi/idporten-oidc-dokumentasjon] Avbryt gir 203007 invalid SAML (#59)


Ei sak som ikkje gjeld dokumentasjonen (men kor elles kan eg sende den?)

Når eg klikker Avbryt/Cancel hos swedenconnect.se (etter å ha vald å autentisere mot svensk eIDAS-node), blir eg sendt tilbake til https://eidas-test1.difi.eon.no/EidasNode/ColleagueResponse og får Unexpected error: 203007 - The SAML message is not valid

**Comment by leivhe** [comment]
sendt per epost
