### ISSUE TITLE
Statuskode 409 på Oppretting av Scope

### ISSUE THREAD

**Issue by anddal** [difi/idporten-oidc-dokumentasjon#65]
Hei,

Jeg følger dokumentasjonen på hvordan man oppretter scopes [her](https://difi.github.io/idporten-oidc-dokumentasjon/oidc_api_admin_maskinporten.html#eksempel-p%C3%A5-%C3%A5-opprette-scope), men får bare 409 Conflict uansett hva jeg poster. Hva gjør jeg feil? 

![image](https://user-images.githubusercontent.com/4533433/52214792-d1b2c100-2892-11e9-9975-15e78f4cb19d.png)

**Comment by joergenb** [comment]
har du blitt korrekt provisjonert?  Ref. https://difi.github.io/idporten-oidc-dokumentasjon/oidc_guide_maskinporten.html#1-manuell-provisjonering

**Comment by anddal** [comment]
Hei igjen @joergenb 

Jeg har sendt inn ønsket provisjonering 05.02.2019, og purret igjen 11.02.2019. Venter fortsatt på svar om ønsket provisjonering fra Fiskeridirektoratet er godkjent. Håper på svar på opprinnelig epost til idporten@difi.no. Kan eventuelt sende inn ønske provisjonering på nytt.

**Comment by joergenb** [comment]
hei @anddal .  Eg har fått oppdatert "oidc_fiskeridirektoratet_api" slik at denne kan administrere API, og registrert fdir som prefix.
