### ISSUE TITLE
Linker til Swagger-dokumentasjon er ødelagt

### ISSUE THREAD

**Issue by ThomasKasene** [difi/idporten-oidc-dokumentasjon#77]
Under https://difi.github.io/idporten-oidc-dokumentasjon/oidc_api_krr.html#endepunkt er det en link til Swagger-dokumentasjonen til "ver2" av REST-API'et som i skrivende stund peker til en 404-side: https://oidc-ver2.difi.no/kontaktinfo-oauth2-server/rest/swagger-ui.html#/Personer

Filen det er snakk om ser ut til å gjelde er:
https://github.com/difi/idporten-oidc-dokumentasjon/blob/gh-pages/pages/oidc/oidc_api_krr.md

**Comment by joergenb** [comment]
takk.  retta opp igjen no.

(vi sliter litt med springfox sin swagger-genereing og måten vi strukturerer applikasjonene våre på, så nokon av urlene inn swaggeren kan framleis vere feil)
